### ISSUE TITLE
Change checkbox input to a text input

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1016]
_This issue is good for beginners. Read [Making your first pull request](https://github.com/ember-learn/guides-source/blob/master/CONTRIBUTING.md#making-your-first-pull-request) and ask for help if you run into issues! Experienced contributors are asked to search for other things to fix._

In [this guide](https://github.com/ember-learn/guides-source/blob/master/guides/release/templates/input-helpers.md) we show using a keyPress event with a checkbox. That seems odd since a click will not trigger updates.

Replace this example with a text input, try it in an app to see if it works, and open a PR with the change. Make sure to check the written sections around the example to see if any of the explanations need to be changed too.

Here's the example that needs to be refactored:

```
<Input @type="checkbox" @keyPress={{action "updateName"}} />
```

Something like this will work:

```
<Input @type="text" @keyPress={{action "updateName"}} />
```

**Comment by asbillings07** [comment]
Could I take a stab at fixing this one?

**Comment by acorncom** [comment]
@asbillings07 please do!

**Comment by asbillings07** [comment]
Awesome. Will get started on it. Thanks!

**Comment by jenweber** [comment]
P.S. if you want to participate in Hacktoberfest, this PR counts! https://hacktoberfest.digitalocean.com/

**Comment by ab-develops-ads** [comment]
Ah okay. I'll take a look at another one I can submit a PR for.

**Comment by viraldevpb** [comment]
can i work on this issue now?

**Comment by ijlee2** [comment]
Hi, @viraldevpb. Thanks for wanting to help out with this issue!

I noticed that the issue is a bit outdated and its description needs to be updated. Currently,

1\. The [Built-in Components](https://guides.emberjs.com/release/components/built-in-components/) page, in versions 3.15 - 3.23, show the correct usage of checkbox inputs.
2\. The [Input Helpers](https://guides.emberjs.com/v3.13.0/templates/input-helpers/) in versions 3.7 - 3.13, as well as [Input Components](https://guides.emberjs.com/v3.14.0/templates/input-components/) in version 3.14, can use an update.
3\. We don't need to change Input Helpers for versions 3.6 and below, because it doesn't talk about how to bind an action to a checkbox input.

## TODOs

### 1. Input Components page (v3.14)

- [ ] Remove the `@name="isAdmin"` in https://guides.emberjs.com/v3.14.0/templates/input-components/#toc_checkboxes. (This better matches the new code example in v3.15.) 
- [ ] Update the code `<Input @type="text" @keyPress={{action "updateName"}} />` to:

    ```handlebars
    <Input @id="admin-checkbox" @type="checkbox" @checked={{this.isAdmin}} @input={{this.validateRole}} />
    ``` 

    Note, it's all 1 line (don't worry about improving the formatting for 3.14).

### 2. Input Helpers page (3.7 - 3.13)

- [ ] Update the code `{{input type="checkbox" keyPress=(action "updateName")}}` to:

    ```handlebars
    {{input type="checkbox" name="isAdmin" checked=this.isAdmin input=(action "validateRole")}}
    ```

    Note, `name="isAdmin"` is kept intact.


## Notes

Can you make 2 commits for your pull request, one for v3.14 and another for v3.7 - v3.13. This will help with the review.

Thanks, and let me know if you have any questions!

**Comment by ejfian-2020** [comment]
Is there any work remaining to be done for this issue ? I can take a stab at it. Thanks

**Comment by ijlee2** [comment]
Hi, @ejfian-2020. Thank you for making time to help out with the issue.

Yes, I think the 2 TODOs listed in my comment above (Jan 3, 2021) are yet to be done. Could you help out with updating the code examples for Ember 3.7 - 3.14?

If a code example shows angle brackets, please use the angle bracket syntax. If curly braces, keep the curly brace syntax. If you have any questions, please let me know!

**Comment by ejfian-2020** [comment]
Hi @ijlee2,
Just so that i understand the asks correctly. This change needs to be done for all the versions of Ember from 3.7 to 3.14 , is that correct ?  
Based on your recommendations I will create 2 PRs one for the v3.14 and another for v3.7- v3.13.

**Comment by ejfian-2020** [comment]
Hi @ijlee2 , 
For v3.10 - v3.13 , the code is using angle brackets and keeping the @name="isAdmin" intact , I will change the 
`<Input @type="text" @keyPress={{action "updateName"}} />`
to

`<Input @id="admin-checkbox" @type="checkbox" @name="isAdmin" @checked={{this.isAdmin}} @input={{this.validateRole}} />`

**Comment by ejfian-2020** [comment]
Hi @ijlee2 , 
For v3.10 - v3.13 , the code is using angle brackets and removing the @name="isAdmin" , I will change the 
`<Input @type="text" @keyPress={{action "updateName"}} />`
to

`<Input @id="admin-checkbox" @type="checkbox" @checked={{this.isAdmin}} @input={{this.validateRole}} />`

Please confirm if the change looks good.
