### ISSUE TITLE
Backport the updated Built-in Components to 3.15, 3.17-3.19

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/guides-source#1566]
## Background

There was a bug in **allowing event names as arguments** (for backwards compatibility) for the `<Input>` and `<Textarea>` components. It's fixed now in versions 3.16 (LTS), 3.20 (LTS), and 3.21 of Ember.

## Problem

We already updated the [Built-In Components](https://guides.emberjs.com/release/components/built-in-components/) page for version 3.21. The changes need to be copied over to versions 3.15 and 3.17-3.19.

The issue is similar to #1556. After copy-pasting the changes from version 3.21, we'll need to provide a warning because the bug wasn't fixed in these versions.

## TODOs

- [ ] Copy the contents of the [release version of `built-in-components.md`](https://github.com/ember-learn/guides-source/blob/master/guides/release/components/built-in-components.md)

- [ ] Paste the contents into 4 files:

    - `guides/source/v3.15.0/components/built-in-components.md`
    - `guides/source/v3.17.0/components/built-in-components.md`
    - `guides/source/v3.18.0/components/built-in-components.md`
    - `guides/source/v3.19.0/components/built-in-components.md`

- [ ] In each Markdown file, update all links that point to `api.emberjs.com` to show the correct version, not `release`.

    ```markdown
    # After copy-paste

    Out of the box, Ember provides 2 components for building a form:

    * [`<Input>`](https://api.emberjs.com/ember/release/classes/Ember.Templates.components/methods/Input?anchor=Input)
    * [`<Textarea>`](https://api.emberjs.com/ember/release/classes/Ember.Templates.components/methods/Textarea?anchor=Textarea)

    # Update the version in the API links (e.g. for `guides/v3.15.0`)

    Out of the box, Ember provides 2 components for building a form:

    * [`<Input>`](https://api.emberjs.com/ember/3.15/classes/Ember.Templates.components/methods/Input?anchor=Input)
    * [`<Textarea>`](https://api.emberjs.com/ember/3.15/classes/Ember.Templates.components/methods/Textarea?anchor=Textarea)
    ```

- [ ] In each Markdown file, copy-paste the following message. It comes after the sentence "The event name ... that the HTML standard uses.":

    ```html
    <div class="cta">
      <div class="cta-note">
        <div class="cta-note-body">
          <div class="cta-note-heading">Tomster says...</div>
          <div class="cta-note-message">
            <p>
              We mention event arguments below to help with Octane upgrade.
              Due to a bug, event arguments do not work in versions 3.15 and 3.17-3.19.
              Please consider using the <code>{{on}}</code> modifier or upgrading to the next LTS (3.16 or 3.20).
            </p>
          </div>
        </div>
        <img src="/images/mascots/tomster.png" role="presentation" alt="">
      </div>
    </div>
    ```

**Comment by ijlee2** [comment]
Hi, everyone. You can now help with this issue! 🎃

Please claim the issue by leaving a comment so that we can assign the issue to you. Thanks, and happy Hacktoberfest!

**Comment by lvegerano** [comment]
I'll take this one

**Comment by ijlee2** [comment]
@lvegerano Thank you in advance for your help!
