### ISSUE TITLE
Epic: make sure we aren't using deprecated or removed methods for Ember 4

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1711]
Read through this list of APIs that are being removed in Ember 4. If we are using any of them in the guides/release folder, comment or open new issues/PRs. Thank you.

The list of removed APIs is in this blog post: [Road to Ember 4](https://blog.emberjs.com/the-road-to-ember-4-0)

[Main Ember 4 tracking issue](https://github.com/emberjs/ember.js/issues/19545)

[Road to Ember 4](https://blog.emberjs.com/the-road-to-ember-4-0)

### Blocking

* `transitionTo`/`transitionToRoute`/`replaceWith`/`replaceWithRoute`
  * deprecation: https://deprecations.emberjs.com/v3.x/#toc_routing-transition-methods)
  * PR: https://github.com/ember-learn/guides-source/pull/1753
  * [x] https://guides.emberjs.com/release/routing/defining-your-routes/#toc_transitioning-between-routes `transitionTo` and `transitionToRoute` on the route and controller respectively should be dropped. 
  * [x] Also at https://guides.emberjs.com/release/routing/preventing-and-retrying-transitions/
  * [x] `replaceWith`, same thing, at https://guides.emberjs.com/release/routing/loading-and-error-substates/
  * [x] `transitionTo`, same thing, at https://guides.emberjs.com/release/routing/query-params/
  * [x] Also https://guides.emberjs.com/release/routing/asynchronous-routing/
* [x] https://github.com/ember-learn/guides-source/issues/1755
* [x] Remove tagName from LinkTo https://github.com/ember-learn/guides-source/pull/1759

### Non-blocking

* [x] #1756
  * https://github.com/ember-learn/guides-source/pull/1758
* [ ] #1757
* [ ] https://github.com/ember-learn/deprecation-app/issues/1034
* [ ] https://github.com/ember-learn/guides-source/issues/1754

### Unclear
* [ ] Need to assert ember-modifiers is compatible with 4.0
* [x] This deprecation guide entry is poorly formatted. The component names should not be part of the list: https://deprecations.emberjs.com/v3.x/#toc_ember-built-in-components-legacy-arguments
* [ ] Some weird promise stuff at https://guides.emberjs.com/release/routing/asynchronous-routing/

### Audit needed

* [ ] Application Development: https://guides.emberjs.com/release/applications/
* [ ] Developer Tools: https://guides.emberjs.com/release/ember-inspector/
* [ ] Additional Resources: https://guides.emberjs.com/release/upgrading/
* [x] Should search for `transition.params` and friends to make sure they aren't used, as deprecated at https://deprecations.emberjs.com/v3.x/#toc_transition-state

**Comment by kategengler** [comment]
The tutorial raises on deprecation, so it shouldn't have anything deprecated.

**Comment by mixonic** [comment]
@jenweber @rajakvk can you provide an update here? We're hopeful about landing Ember 4.0 in the coming week or so, and this would become a blocker.

**Comment by mixonic** [comment]
I looked through **Core Concepts** and **Introduction**(minus the tutorial).

Critical to address:

* At https://guides.emberjs.com/release/routing/defining-your-routes/#toc_transitioning-between-routes `transitionTo` and `transitionToRoute` on the route and controller respectively should be dropped. See https://deprecations.emberjs.com/v3.x/#toc_ember-built-in-components-legacy-arguments
* Same at https://guides.emberjs.com/release/routing/redirection/, lots of deprecated transition APIs in the guide.
* Also at https://guides.emberjs.com/release/routing/preventing-and-retrying-transitions/
* `replaceWith`, same thing, at https://guides.emberjs.com/release/routing/loading-and-error-substates/
* `transitionTo`, same thing, at https://guides.emberjs.com/release/routing/query-params/
* Also https://guides.emberjs.com/release/routing/asynchronous-routing/
* Should search for `transition.params` and friends to make sure they aren't used, as deprecated at https://deprecations.emberjs.com/v3.x/#toc_transition-state
* `<LinkTo` and `@tagName` used at https://guides.emberjs.com/release/models/#toc_the-store-and-a-single-source-of-truth removed per https://deprecations.emberjs.com/v3.x/#toc_ember-built-in-components-legacy-arguments
* `transitionTo` at https://deprecations.emberjs.com/v3.x/#toc_ember-built-in-components-legacy-arguments

Not critical:

* https://guides.emberjs.com/release/components/looping-through-lists/ - This example uses `A(` for ember array. For app authors getting started, this is not necessary. Only users who would like to disable prototype extensions and use array mutation with tracking must use that API. For beginners, IMO we should not teach it.
* Need to assert ember-modifiers is compatible with 4.0
* This deprecation guide entry is poorly formatted. The component names should not be part of the list: https://deprecations.emberjs.com/v3.x/#toc_ember-built-in-components-legacy-arguments
* The error catching flow in https://guides.emberjs.com/release/routing/defining-your-routes/#toc_wildcard--globbing-routes is not ideal, it swallows all errors silently. Also, promise API is being used inside an `async` function which is not needed.
* Some weird promise stuff at https://guides.emberjs.com/release/routing/asynchronous-routing/

Remaining sections to audit:

* Application Development: https://guides.emberjs.com/release/applications/
* Developer Tools: https://guides.emberjs.com/release/ember-inspector/
* Additional Resources: https://guides.emberjs.com/release/upgrading/

**Comment by jenweber** [comment]
Hi @mixonic thanks for your help with the QA! We have one merged PR that addressed a lot of routing things, and I’ll check that it’s live. I also have an open PR updating a lot of classic content. After work I’ll cross reference those to see where we still have gaps.

**Comment by locks** [comment]
@mixonic can you elaborate on these three points? I am not sure I understand what needs to happen for each:

- Need to assert ember-modifiers is compatible with 4.0
- This deprecation guide entry is poorly formatted. The component names should not be part of the list: https://deprecations.emberjs.com/v3.x/#toc_ember-built-in-components-legacy-arguments
- Some weird promise stuff at https://guides.emberjs.com/release/routing/asynchronous-routing/

**Comment by bertdeblock** [comment]
> This deprecation guide entry is poorly formatted.

I think this PR should improve that: https://github.com/ember-learn/deprecation-app/pull/1035

**Comment by locks** [comment]
🎉
