### ISSUE TITLE
Feature Epic - Cross Site Search

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1954]
These tasks should go into a project board as separate tickets once contributors are ready to work on them.

To do:

- [ ] communicate in search experience for each part of the site that search is only
searching a specific site (quick win). Include the name of what you are searching in the search box placeholder and in the search results. Talk to @MinThaMie if you would like to help with this!
- [ ] implement the proof of concept for the search page idea. Talk to @mansona if you would like to help with this!
- [ ] Gather user feedback about the search page. Is it useful? What tweaks would someone make? Talk through the order/content. - [ ] Evaluate whether the kind of results that land in a search page would be ok for a modal.
- [ ] If ☝️ seems good, move the search to a modal
