### ISSUE TITLE
Quest: Octane Guides MVP Tracking issue

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#394]
Hello and thanks so much for helping out with the Octane Guides! Even if you don't know much about Octane or Native Classes, there's something you can help with! Here's everything you need to know to pitch in. 

The "new volunteers needed" links below that are the things we need help with more than anything else. We are aiming to finish a rough draft of the Guides by March 15th. If you volunteer for an issue, please only do so if you can have a PR with at least part of the work ready the following evening after you claim the issue. To volunteer, comment in the linked issue (not here) to say that you can help. You should `git branch` from the [octane branch](https://github.com/ember-learn/guides-source/tree/octane) of the Guides, do work in the markdown files in the `guides/release` directory, and when you open a PR, make it go the `octane` branch. If you want to learn the basics of what's different in Octane, have a read through [this draft guide](https://github.com/ember-learn/guides-source/blob/octane/guides/release/upgrading/editions.md).

## New volunteers needed:
Please check the comments on issues to see if they are already claimed. Are they all taken? Pick a different section of the guides, copy and paste the contents of one of the "JavaScript Code Blocks to use Class Syntax" issues for a section that's not in this list, open an issue, and put at the top that you're helping with it! You can grab just one page, or a whole section. It's up to you!

- [create a new section, services](https://github.com/ember-learn/guides-source/issues/461) - requires no Octane knowledge
- [Change Quickstart JavaScript Code Blocks to use Class Syntax](https://github.com/ember-learn/guides-source/issues/541) - good for someone who wants to learn class syntax, since there are a small # of code blocks
- [Change Writing Helpers JavaScript code blocks to use Class Syntax](https://github.com/ember-learn/guides-source/issues/542) - good for someone who wants to learn class syntax, since there are a small # of code blocks
- [Change Tutorial examples to use Class Syntax](https://github.com/ember-learn/guides-source/issues/540) - helpful to know Native Classes already, since this one is a lot of work. Who is bold, and daring!?!? It's ok to open a PR the next day that's incomplete.
- [Change Ember Data examples to use Class Syntax](https://github.com/ember-learn/guides-source/issues/543) - helpful to know Native Classes already, since this one is a lot of work. Who is bold, and daring!?!? It's ok to open a PR the next day that's incomplete.

## High level tracking, in progress:

This section is purely for tracking how much work we still have left to do, in a very broad sense.

- [x] Re-order TOC (as per RFC) [issue #393]

Content Sections:
- [x] What is Ember?
- [x] Getting Started [issue #444]
- [x] Tutorial 
- [x] Templates [issue #460]
- [x] Working with JavaScript [issue #429]
- [x] Components [issue #395]
- [x] Routing (includes Routes, Router, and Controllers) [issue #438]
- [x] State management (aka computed properties)
- [x] Services [issue #461]
- [x] Ember Data (renamed from "Models")
- [x] Addons and dependencies (no change)
- [x] Testing (no change) 
- [x] Configuration (no change)
- [x] Application Concerns [issue #449]
- [x] Developer Tools (renamed from "Ember Inspector")
- [x] Upgrading (specifically Editions sub-section) [issue #463]
- [x] References

**Comment by rtablada** [comment]
The content sections mentions `Tutorials` does this entail breaking the tutorials out to the separate repo, the Contact Book content, or both?

**Comment by jenweber** [comment]
@rtablada the plan is long term to break out the tutorials into a separate repo/app, but we need to focus on content first, and then infra after the first Octane release.

**Comment by ppcano** [comment]
It may be good to review what content needs to change regarding the `MU layout` and/or add a particular section?

**Comment by MelSumner** [comment]
Just to gently remind all of us, this is just supposed to be a minimum viable product.

**Comment by MonsieurDart** [comment]
Hello @MelSumner! Do we still have some parts of the guides to migrate to the new syntax? From my understanding, everything has been migrated. If not, I can tackle some of the remaining bits. 

And, by the way, is there a way to see this new Guides MVP formatted somewhere? My question is a bit off-topic, but I have two newcomers arriving next week and I'd love them to start discovering Ember with the new syntax from day one! 😉

**Comment by NullVoxPopuli** [comment]
do some of these checkboxes need updating?

**Comment by jenweber** [comment]
I checked them all, mwahahaha.

Thanks everyone for your help! As of EmberConf 2019, we reached MVP for the Octane Guides 🎉  

Anyone who wants to see the outcomes can visit https://emberjs.com/editions/octane for the preview guides. Octane isn't in a stable release of Ember - this is a preview - but we are in really good shape for when it's time to ship.
