### ISSUE TITLE
Octane guides: Component section (tracking issue)

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#395]
PM TODO: create issues for each of these sub-sections, and add issue to this tracking issue

Components will need the most refactor work and new content for Octane, so here’s the subtopic breakdown:

- [ ] Creating a component (includes Component Types post-Octane) [issue #396]
- [x] Displaying data in a Template [issue #397]
- [x] Adding actions [issue #398 ]
- [ ] Nesting components (includes suggestions of when to break things into components) [issue #428]
- [x] Passing arguments [issue #431]
- [ ] Using computed properties (extremely basic example, link to the Computed Property section)
- [ ] Working with arrays of data
- [ ] Lifecycle hooks

**Comment by chancancode** [comment]
I'm working on documentation for how to work with DOM in Octane (replacement for lifecycle hooks). It should be in an MVP state in the next day or so.

**Comment by wycats** [comment]
I'm working on documentation for working with the DOM in Octane. It should be ready in an MVP state in the next day or so.

**Comment by Frozenfire92** [comment]
was about to make an issue when I came across this one

![Screen Shot 2019-03-17 at 1 02 40 PM](https://user-images.githubusercontent.com/5893112/54494049-f7c97900-48b4-11e9-8dd6-c226c8db7ecd.png)

It seems there are two links which are covering DOM manipulation

`Interactiving with the DOM`: `/release/components/interacting-with-the-dom/`
`Working with the DOM`: `/release/components/glimmer-components-dom/`

The first of which is broken (non existent file)

I suspect the first heading/url is desired based on ` "Interacting with the DOM", url: "interacting-with-the-dom"` in #588

**Comment by wycats** [comment]
Is this still being updated?

**Comment by jenweber** [comment]
Closed, I think we have hit all these points. Thanks all!
