### ISSUE TITLE
Update Octane guides sub-section: Components > Adding actions

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#398]
## Goal
Update the "adding actions" sub-section of the Components section of the Octane guides so it includes how to do components in a way that is consistent with the Octane edition of Ember. 

## TODO
- [ ] Translate to native classes
  - [ ] class definition
  - [ ] `@action` decorator on actions
- [ ] Update templates not to use string actions
- [ ] Add a header about string actions

## References
This issue is a part of the [Component section tracking issue](https://github.com/ember-learn/guides-source/issues/395)

**Comment by knownasilya** [comment]
@locks for `* Add a header about string actions` what specifically should this cover?

**Comment by knownasilya** [comment]
And making sure that this is the right file: https://github.com/ember-learn/guides-source/blob/octane/guides/release/components/triggering-changes-with-actions.md

**Comment by locks** [comment]
> @locks for `* Add a header about string actions` what specifically should this cover?

@knownasilya what I meant by it is that doing `{{action 'myAction'}}` is considered legacy in the Octane universe, but we still have to document it for interop reasons.

**Comment by knownasilya** [comment]
Sort of a migration guide and warning, got it.
