### ISSUE TITLE
Update Octane guides section - Getting Started: Core Concepts

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#434]
You should target the `octane` branch with your PR.

## Goal
Update the "Controllers" section of the Octane guides so it is consistent with the Octane edition of Ember. 

## TODO
- [ ] Update code samples to native class and decorators
- [ ] Update code sample paths to Octane layout paths
- [ ] Update images for native classes and Octane layout

**Comment by MelSumner** [comment]
@locks @jenweber I thought we were moving Controllers to a sub-section for Routing?

**Comment by locks** [comment]
@MelSumner we can move it before/after this work is done. I had in mind an iterative approach where we get the mechanical conversions out the way and then focus on re-arranging.

**Comment by jenweber** [comment]
Closed by lots of PRs right before EmberConf. Thank you!
