### ISSUE TITLE
 Update Octane guides section - Routing

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#438]
Your PR should target the `octane` branch.

## Goal
Update the "Routing" section of the Octane guides so it is consistent with the Octane edition of Ember. 

## Tasks
- Defining your routes
  - [ ] Update `{{link-to}}`.
- Specifying a route's model
  - [ ] Update for native classes.
  - [ ] Update `{{link-to}}`.
- Rendering a template
  - [ ] Update for native classes.
- Redirecting
  - [ ] Update for native classes.
- Preventing and retrying transitions
  - [ ] Update for native classes.
  - [ ] Update `{{link-to}}`.
- Query parameters
  - [ ] Update for native classes.
  - [ ] Update `{{link-to}}`.
- Asynchronous Routing
  - [ ] Update for native classes.

**Comment by NullVoxPopuli** [comment]
Looks like these are all added already?

**Comment by locks** [comment]
Thanks for double checking!
