### ISSUE TITLE
 Update Octane guides section - Configuring Ember.js: Debugging

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#440]
Your PR should target the `octane` branch.

## Goal
Update the "Embedding Applications" sub-section of the Octane guides so it is consistent with the Octane edition of Ember. 

## TODO
- [ ] Update code samples to native class and decorators
- [ ] Update code sample paths to Octane layout paths
- [ ] Update for runloop changes (needs investigating)
