### ISSUE TITLE
Change Tutorial JavaScript code blocks to use Class Syntax

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#540]
We'd love to have a volunteer for this! Please see [Octane MVP](https://github.com/ember-learn/guides-source/issues/394) for instructions about where to make your PR. Please only volunteer for this issue if you can open a PR with at least part of the work by the end of the next day. Thanks for your help!

### To-do
For this issue, we should only make "class syntax" changes to the code blocks within `guides/release/tutorial` markdown files. Later PRs will fix up the written explanations to go with them. Here's an example of converting to Class syntax:

```js
// Before
import Controller from '@ember/controller';

export default Controller.extend({
  title: 'hello-world.app',
});
```

```js
// After
import Controller from '@ember/controller';

export default class ApplicationController extends Controller {
  title = 'hello-world.app';
}
```

- [ ] branch from the `octane` branch of the guides
- [ ] See [this guide's Native Classes](https://github.com/ember-learn/guides-source/blob/octane/guides/release/upgrading/editions.md#native-classes) explanation to learn about the changes you will have to make
- [ ] Make changes to the code blocks to use class syntax
- [ ] PR to the `octane` branch

**Comment by muziejus** [comment]
I volunteer. Is that sufficient warning to ensure I don't stomp on someone else's work?

**Comment by jenweber** [comment]
Yep! Thanks for the help! Let me know if you have any questions along the way.

**Comment by jamescdavis** [comment]
I volunteer to CR this when the PR is opened. @muziejus, please ping me on the PR.

**Comment by muziejus** [comment]
My one question so far, I think, is about whether I should _also_ be adding decorators?

```javascript
export default class BlahComponent extends Component {
  actions = {
    handleClick() {
     // ...
    }
  }
}
```

looks odd to me.  It wouldn't be much...

**Comment by rajasegar** [comment]
@muziejus Yes i think, should be
```js
export default class BlahComponent extends Component {
  @action
    handleClick() {
     // ...
    }

}
```

**Comment by muziejus** [comment]
OK, I'll add decorators then.

Another question: tests fail on broken links outside of my realm… and the one inside my realm seems unfixable:

```
3260 passing (5s)
  4 failing

  1) check all links in markdown files
       processing guides/release/components/block-params.md:
     AssertionError: [ { fileToFix: 'guides/release/components/block-params.md',
    badLink: '../passing-properties-to-a-component/' } ]: expected [ Array(1) ] to be empty
      at Context.<anonymous> (node-tests/link-checker.js:38:54)

  2) check all links in markdown files
       processing guides/release/components/wrapping-content-in-a-component.md:
     AssertionError: [ { fileToFix:
     'guides/release/components/wrapping-content-in-a-component.md',
    badLink: '../passing-properties-to-a-component/' } ]: expected [ Array(1) ] to be empty
      at Context.<anonymous> (node-tests/link-checker.js:38:54)

  3) check all links in markdown files
       processing guides/release/reference/syntax-conversion-guide.md:
     AssertionError: [ { fileToFix: 'guides/release/reference/syntax-conversion-guide.md',
    badLink:
     '../../components/passing-properties-to-a-component/#toc_positional-params' } ]: expected [ Array(1) ] to be empty
      at Context.<anonymous> (node-tests/link-checker.js:38:54)

  4) check all links in markdown files
       processing guides/release/tutorial/autocomplete-component.md:
     AssertionError: [ { fileToFix: 'guides/release/tutorial/autocomplete-component.md',
    badLink:
     '../../components/triggering-changes-with-actions/#toc_passing-the-action-to-the-component' } ]: expected [ Array(1) ] to be empty
```

**Comment by jenweber** [comment]
Adding decorators would be awesome!

**Comment by jenweber** [comment]
Regarding tests, go ahead and open a PR against Octane and we’ll figure out test failures later. We aren’t running CI against that branch yet, due to unfinished redirects

**Comment by rajasegar** [comment]
I figured out the test case failures, those are addressed here
https://github.com/ember-learn/guides-source/pull/552

**Comment by muziejus** [comment]
@jenweber With the merged PR #551, I think this is now closed?

**Comment by acorncom** [comment]
@muziejus it looks like it, thanks!
