### ISSUE TITLE
Change Ember Data JavaScript code blocks to use Class Syntax

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#543]
We'd love to have a volunteer for this! Please see [Octane MVP](https://github.com/ember-learn/guides-source/issues/394) for instructions about where to make your PR. Please only volunteer for this issue if you can open a PR by the end of the next day. Thanks for your help!

### To-do
For this issue, we should only make "class syntax" changes to the code blocks within `guides/release/models` markdown files. Later PRs will fix up the written explanations to go with them. Here's an example of converting to Class syntax:

```js
// Before
import Controller from '@ember/controller';

export default Controller.extend({
  title: 'hello-world.app',
});
```

```js
// After
import Controller from '@ember/controller';

export default class ApplicationController extends Controller {
  title = 'hello-world.app';
}
```

- [ ] branch from the `octane` branch of the guides
- [ ] See [this guide's Native Classes](https://github.com/ember-learn/guides-source/blob/octane/guides/release/upgrading/editions.md#native-classes) explanation to learn about the changes you will have to make
- [ ] Make changes to the code blocks to use class syntax
- [ ] PR to the `octane` branch

**Comment by efx** [comment]
I'll grab this one.

**Comment by jenweber** [comment]
Thanks Eli!!!

**Comment by acorncom** [comment]
@efx anything else needed here?

**Comment by efx** [comment]
@acorncom Tutorials related to ember-data haven't been converted IIRC. I'll check on this today and do a once over of the current status.

**Comment by efx** [comment]
@jenweber @acorncom this should be done now. There are other aspects of decorators and native classes to address as discussed in #603, but they fit better as part of other PR's / contained issues.

**Comment by jenweber** [comment]
Thanks everyone for the help! Closed.
