### ISSUE TITLE
Quest - Changes we need to make before the official release of Octane Guides

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#669]
The Learning team needs your help getting Octane ready to ship on emberjs.com! To help out, please do your work in the `guides/release` folder of the `octane` branch, and open PRs back into `octane`.

This issue described is MVP to merge the guides for 3.14. You can see the current Octane preview guides at https://octane-guides-preview.emberjs.com/release/

### URL persistence
- [x] writing redirects from old pages to new, #719  PR #1210 

### Version upgrade guide
- [x] Rework the conversion guide to be readable/useful in both directions (to an from Octane)
- [x] Revise the Upgrade Guide intro to be short & sweet - has PR by JW https://github.com/ember-learn/guides-source/pull/796
- [x] Link to examples in the upgrade guides, instead of using new examples (for example, show "old version" of syntax and link to the "new version"

### Syntax updates
- [x] document `{{on}}` (see https://github.com/emberjs/rfcs/blob/master/text/0471-on-modifier.md) - @sivakumar-kailasam is doing this
- [x] document `{{fn}}`(see https://github.com/emberjs/rfcs/blob/master/text/0470-fn-helper.md) @sivakumar-kailasam is doing this
- [x] show angle brackets versions of LinkTo and Input (refer to them as "built in components" - done by https://github.com/ember-learn/guides-source/pull/696 and JW #797 
- [x] search for computed properties and replace them with tracked. (There should only be 1 section where we talk about interop between tracked and CPs.) JW partially addressed in #805 
    - [x] Make sure that we have a section on interop, and write it if needed
- [ ] Make sure that Ember Data code samples actually work
- [ ] make sure tests work

### Octane tutorial

This is involved, probably 20 hours of work that will need to be divided up.

- [x] Bring the Tutorial prose up to speed to use Glimmer Components, Tracked, etc. Goes with the next item below.
- [x] Make a version of Super Rentals that uses Octane - WIP by VJ - see https://github.com/ember-learn/super-rentals/issues/118)

### Quick fixes
- [x] Search for uses of the word "Glimmer" and remove them unless they are referencing the package name. In one or two places, explain that glimmer is the rendering engine and you don't need to learn the library itself directly - has PR by JW  https://github.com/ember-learn/guides-source/pull/796
- [x] In the section about the Router, add a note that it's an Ember Object and not a class (note by JW - we don't even show the full router boilerplate and people only edit the map, so this is ok as-written in the Guides)
- [x] Remove typescript example - has PR by JW  https://github.com/ember-learn/guides-source/pull/796

### Editing

The guides are 100+ pages. We need to make sure they reflect modern Ember.

- [x] read topics to see if they flow together
    - [x] Components, start to finish
    - [x] Routing, start to finish
- [x] make sure there is a good intro for each new page 
- [x] De-duplicate explanations. Find the places where we should link rather than re-explain
- [x] remove any remaining references to EmberObject, unless it's to explain that it's an old thing replaced by classes

### Undoing shortcuts

These should happen at the very end.

- [x] hiding the versions dropdown https://github.com/ember-learn/guides-source/pull/667#pullrequestreview-215866017
- [x] hiding the edit pencil and search bar https://github.com/ember-learn/guides-source/pull/616
- [x] revert changes to Google Analytics and Robots.txt #610 

### Stretch goals
- [x] diagrams and images
- [x] split up the conversion guide somehow (needs discussion)
- [ ] Services needs more details

### Open questions
- [ ] Is Ember Data enabling `hasMany` instead of `hasMany()`?
- [x] renaming Components topics?

**Comment by jenweber** [comment]
This is a future thing, for a month or two from now.

We're making a staging app at https://octane-preview-guides.emberjs.com, and with it comes some cleanup work

We committed to "maintaining" this staging app via redirects to our main guides, once we take it down. Tom, Yehuda, Jen, Mel, and Chris all discussed this on March 13th and the decision to support redirects was a requirement for agreement on the app plan. Basically, we don't want to lose SEO powers and also we have a responsibility to our users to not break blog post links and all that.

(formerly #609)

**Comment by MelSumner** [comment]
https://octane-guides-preview.emberjs.com/release/components/yields/ should be updated so it doesn't use a modal. They are tricky for many reasons, accessibility being one of them.

**Comment by bertdeblock** [comment]
Does https://github.com/emberjs/data/pull/6339 answer `Is Ember Data enabling hasMany instead of hasMany()?`. That PR added support for using the `attr`, `belongsTo` and `hasMany` decorators without parens.

**Comment by chancancode** [comment]
@bretdeblock go ahead and use it without paren in the guides

**Comment by bertdeblock** [comment]
@chancancode I issued a PR. I came across some other things as well but did not want to clutter this PR. How would I go about making additional changes? One PR with various separate commits or are multiple PRs preferred?

**Comment by sly7-7** [comment]
@jenweber @MelSumner I made some little prs against the octane branch, hope this helps.
See https://github.com/ember-learn/guides-source/pull/1174 https://github.com/ember-learn/guides-source/pull/1175 https://github.com/ember-learn/guides-source/pull/1173
