### ISSUE TITLE
Switch to <AngleBracket /> built-in components on Octane branch (input, link-to, etc)

### ISSUE THREAD

**Issue by chancancode** [ember-learn/guides-source#692]
It's time to switch the Octane guides to use <AngleBracket /> built-in components!

* `{{link-to}}` -> `<LinkTo />`
* `{{input}}` -> `<Input />`
* `{{textarea}}` -> `<Textarea />`

This should mostly just be a syntactic change, but we could also take the opportunity to adjust the flow, remove legacy concepts, etc. For example, since angle bracket invocation takes HTML attributes, we can update the examples to pass them directly (i.e. `class=` instead of `@class=`).

To help out, please leave a comment to "claim" the item (🔒 below) so others know not to duplicate the effort! It's fine to claim the item before you have a PR ready (but please release it if it turns out you didn't have the time to do it). Branch from the `octane` branch of the Guides and open your PR to be merged back into `octane`. Thank you!

Some resources:

* See PR #681 for an example
* [RFC #459](https://emberjs.github.io/rfcs/0459-angle-bracket-built-in-components.html) for details about the feature
* [API docs PR](https://github.com/emberjs/ember.js/pull/17810)

Guides that need to be updated:

* [x] `components/actions-and-events.md` (:lock: @alexBaizeau ~~#697~~)
* [x] `models/index.md` (🔒 @chancancode ~~#681~~)
* [x] `routing/defining-your-routes.md` (🔒 @chancancode ~~#681~~ ~~#693~~)
* [x] `routing/preventing-and-retrying-transitions.md` (🔒 @chancancode ~~#681~~)
* [x] `routing/query-params.md` (:lock: @alexBaizeau ~~#698~~)
* [x] `routing/specifying-a-routes-model.md` (:lock: @Charizard ~~#699~~)
* [x] `templates/binding-element-attributes.md` (🔒 @chancancode ~~#681~~)
* [x] `templates/input-helper.md` (:lock: @ddoria921 #696)
* [x] `templates/links.md` (🔒 @chancancode ~~#681~~)
* [x] `testing/testing-components.md` (:lock: @Charizard ~~#700~~)
* [x] `tutorial/auto-complete-component.md` (:lock: @zachgarwood ~~#702~~)
* [x] `tutorial/model-hook.md` (:lock: @mdbiscan ~~#704~~)
* [x] `tutorial/routes-and-templates.md` (:lock: @ClaytonTurner ~~#705~~)
* [x] `tutorial/simple-component.md` (:lock: @mdbiscan ~~#706~~)
* [x] `tutorial/subroutes.md` (:lock: @dknutsen ~~#707~~)
* [x] `upgrading/editions.md` (:lock: @mdbiscan ~~#709~~)

**Comment by chancancode** [comment]
When you are about to start working on one of these, please leave a comment to "claim" the item so others know not to duplicate the effort!

**Comment by alexBaizeau** [comment]
I'm claiming `components/actions-and-events.md`

**Comment by alexBaizeau** [comment]
I'm claiming `routing/query-params.md`

**Comment by Charizard** [comment]
Would like to claim `routing/specifying-a-routes-model.md`

**Comment by Charizard** [comment]
Would like to claim `testing/testing-components.md`

**Comment by zachgarwood** [comment]
It appears that `tutorial/autocomplete-component.md` has already been angle-bracket-ized.

**Comment by mdbiscan** [comment]
I'll take the next one, `tutorial/model-hook.md`

**Comment by ClaytonTurner** [comment]
I'll claim the one after that: `tutorial/routes-and-templates.md`

**Comment by mdbiscan** [comment]
I'll claim tutorial/simple-component.md.

**Comment by dknutsen** [comment]
I'll claim tutorial/subroutes.md

**Comment by mdbiscan** [comment]
Happy to claim upgrading/editions.md

**Comment by uchihamalolan** [comment]
Happy to claim `templates/input-helper.md`

**Comment by jenweber** [comment]
Thanks everyone for your help with these changes! And thank you @chancancode for coordinating.

We finished the last file in #753 plus some prose in #696
